name: Components to Documents
on:
  push:
    paths:
      - templates/meshmodel/components**
  release:
    types: [published]

jobs:
  CopyComponents:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Make components to .md files
        run: |
            
            function join_by {
              local d=${1-} f=${2-}
              if shift 2; then
                echo "$f${@/#/$d}"
                
              fi
            }
            mkdir output
            folder_path=templates/meshmodel/components/*
            for file in $folder_path;
            do
                folder_name="$file/*"
                onlyfolder=$(basename "$file")
                echo "---
            component: $onlyfolder
            integrations:" > $onlyfolder.md
                for indFile in $folder_name;
                do
                    filename=$(basename "$indFile")
                    temp_filename=$filename
                    IFS="."
                    read -ra newarr <<< "$temp_filename"
                    IFS=""
                    if [[ "${newarr[7]}" == "schema" ]]
                    then
                        continue
                    fi
                    ans=$(join_by . ${newarr[0]} ${newarr[1]})
                    echo "    - $ans" >> $onlyfolder.md
                  done
                echo "---" >> $onlyfolder.md
            mv $onlyfolder.md output
            done

      - name: Pushes folder to main repo
        uses: crykn/copy_folder_to_another_repo_action@v1.0.6
        env:
          API_TOKEN_GITHUB: ${{ secrets.GH_ACCESS_TOKEN }}
        with:
          source_folder: 'output'
          destination_repo: 'meshery/meshery'
          destination_folder: 'docs/_integrations/istio'
          destination_branch: 'master'
          user_email: 'ci@layer5.io'
          user_name: 'l5io'
          commit_msg: 'Adapters Component added'