name: Test Istio Adapter - control plane 

on:
  push:
    branches:
      - "*"
    tags:
      - "v*"
  pull_request:
    branches:
      - "*"
  release:
    types: [published]
jobs:
  SetPatternfile:
    runs-on: ubuntu-latest
    outputs:
      sm_version: ${{ steps.gettag.outputs.release }}
      adapter_version:  ${{ env.version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get version of adapter
        run: |
            if [ ${{ github.event_name }} == "release" ];then
                echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            else 
                echo "version=edge" >> $GITHUB_ENV
            fi
      - name: Get latest release tag
        id: gettag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: istio/istio
          excludes: prerelease, draft, edge 
      - name: Change service mesh version in patternfile
        run: | 
           yq e -i '.services.istio.settings.version="${{ steps.gettag.outputs.release }}"' ./.github/install/deploy.yaml 
           cat ./.github/install/deploy.yaml
      - name: Uploading file
        uses: actions/upload-artifact@v2
        with:
          name: patternfile
          path: ./.github/install/deploy.yaml 

  TestIstio:
    needs: SetPatternfile
    uses: meshery/meshery/.github/workflows/testadapters.yaml@master
    with:
      expected_pods: istiod,istio-egressgateway,istio-ingressgateway
      expected_pods_namespaces: istio-system,istio-system,istio-system
      deployment_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-istio-deployment.yaml
      service_url: https://raw.githubusercontent.com/meshery/meshery/master/install/deployment_yamls/k8s/meshery-istio-service.yaml
      adapter_name: istio
      patternfile_name: deploy.yaml
      provider: Local
      k8s_version: v1.20.1
      sm_version: ${{ needs.SetPatternfile.outputs.sm_version }}
      adapter_version:  ${{ needs.SetPatternfile.outputs.adapter_version }}
      output_filename: data.json
    secrets:
      token: ${{ secrets.PROVIDER_TOKEN }} 

  UpdateDocs:
    needs: TestIstio
    if:  "always() && github.event_name != 'pull_request' "
    runs-on: ubuntu-latest
    steps:
      - name: Skip if needed
        run: |
            echo "this is it ${{ needs.SkipIfNeeded.outputs.skipdocupdate }} "
            if [ "${{github.event_name }}" == "push" ];then
              echo "version=edge" >> $GITHUB_ENV
            fi
            if [ "${{github.event_name }}" == "release" ];then
              echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
            fi
      - uses: actions/checkout@master
        with:
          repository: meshery/meshery 
          token: ${{ secrets.GITHUB_TOKEN }}   
      - name: DownloadJSON
        uses: actions/download-artifact@v2
        with:
          name: data.json
      - name: echo results
        run: |
          pretty=$(jq . data.json)
          rm data.json

          cd ./docs/_compatibility/meshery-istio
          touch data.json
          echo $pretty > data.json
          cat data.json
          touch test.md
          filename=$(date '+%Y-%m-%d-%H:%M:%S')
          echo $filename
          echo "---
          timestamp: $(jq '.metadata.runon' data.json)
          meshery-component: meshery-istio
          meshery-component-version: $version
          meshery-server-version: $(jq '.metadata."meshery-server-version"' data.json)
          k8s-distro: minikube
          k8s-version: $(jq '.metadata.k8s_version' data.json)
          service-mesh: istio
          service-mesh-version: $(jq '.metadata.service_mesh_version' data.json)
          tests:
            istiod: $(jq '.pods_status."istiod"' data.json)
            istio-egressgateway: $(jq '.pods_status."istio-egressgateway"' data.json)
            istio-ingressgateway:  $(jq '.pods_status."istio-ingressgateway"' data.json)
          overall-status: $(jq '."overall-status"' data.json)
          ---" >  test.md
          mv test.md $filename.md
          rm data.json
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: docs
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: '--signoff'
          commit_message: '[Docs] Test status of adapter'
