name: Meshery Istio Pattern Components Generator
on:
  push:
    branches:
      - 'master'
  schedule:
  - cron: "0 0 * * *"
jobs:
  GenerateComponents:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - name: Build jsonschema util
      run: |
          wd=$(pwd)
          mkdir -p ~/.meshery/bin
          cd ~/.meshery/bin
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
          nvm install v14.15.3
          nvm install-latest-npm
          git clone https://github.com/layer5io/kubeopenapi-jsonschema util
          cd util
          npm i; npm i nexe -g
          make linux
          cd ..
          mv ./util/kubeopenapi-jsonschema kubeopenapi-jsonschema
          pwd;ls
          cd $wd
    - name: Run adapter to create components
      run: |
        touch log.txt
        (FORCE_DYNAMIC_REG=true DEBUG=true go run main.go > log.txt 2>&1) &  
        end=$((SECONDS+300))
        while [ $SECONDS -lt $end ]; do
            if  [ "$(cat log.txt | grep "Component Creation completed for version")" != "" ];then
                echo "New components created"
                break
            fi
        done
        rm log.txt
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: templates/
        commit_user_name: l5io
        commit_user_email: ci@layer5.io
        commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit_options: '--signoff'
        commit_message: "[Patterns] Pattern components generated from latest Istio manifests"
