name: Meshery Istio Pattern Components Generator
on:
  push:
    branches:
      - 'master'
  schedule:
  - cron: "0 0 * * *"
jobs:
  GenerateComponents:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - name: Download KubeOpenAPI binary
      run: |
        wd=$(pwd)
        mkdir -p ~/.meshery/bin
        cd ~/.meshery/bin
        Version=$(curl --silent "https://api.github.com/repos/layer5io/kubeopenapi-jsonschema/releases/latest" |                          
        grep '"tag_name":' |
        sed -E 's/.*"([^"]+)".*/\1/')
        curl -L https://github.com/layer5io/kubeopenapi-jsonschema/releases/download/$Version/kubeopenapi-jsonschema --output ./kubeopenapi-jsonschema
        cd $wd
        (FORCE_DYNAMIC_REG=true DEBUG=true go run main.go > log.txt 2>&1) &  #start the adapter
        end=$((SECONDS+100))
        while [ $SECONDS -lt $end ]; do
            donelog-$(cat log.txt | grep "Component Creation completed for version")
            if  [ donelog != "" ];then
                echo "New components created"
            fi
        done
        rm log.txt
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        file_pattern: templates/
        commit_user_name: l5io
        commit_user_email: ci@layer5.io
        commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        commit_options: '--signoff'
        commit_message: "[Patterns] Pattern components generated from latest Istio manifests"
